
# 配置项官方文档: https://gohugo.io/getting-started/configuration/


defaultContentLanguage = "custom"
title = "Kaneha's Blog"
theme = 'hextra'


[markup.highlight]
# 设置为false会启用主题的高亮, 设置为true会使用hugo默认的高亮
noClasses = false

[params.theme]
default = "system"
displayToggle = true

# 右上角菜单配置
[[menu.main]]
name = "我的笔记"
pageRef = "/docs"
weight = 1
[[menu.main]]
name = "Search"
weight = 2
  [menu.main.params]
  type = "search"
[[menu.main]]
name = "GitHub"
weight = 3
url = "https://github.com/kaneha/hugo"
  [menu.main.params]
  icon = "github"

