# 注意: 
#   一些主题会有很多配置文件, 安装主题时会要求把这些配置文件放入config目录,
#   而根目录的hugo.toml(此文件) 的优先级低于config下的配置文件, 
#   所以使用那些主题时, 根目录的hugo.toml(此文件)不生效.
#   我现在正在用的是Blowfish主题, 此文件不生效.
# baseURL = 'https://example.org/'
# languageCode = 'en-us'
# title = "Kaneha's Blog"
theme = 'stack'



[module.hugoVersion]
extended = true
min = "0.87.0"

[params]
mainSections = [ "software", "website-build" ]
featuredImageField = "image"
rssFullContent = true

  [params.footer]

  [params.dateFormat]
  published = "Jan 02, 2006"
  lastUpdated = "Jan 02, 2006 15:04 MST"

  [params.sidebar]
  compact = false

    [params.sidebar.avatar]
    enabled = true
    local = true
    src = "img/avatar.png"

  [params.article]
  math = false
  toc = true
  readingTime = true

    [params.article.license]
    enabled = false
    default = "Licensed under CC BY-NC-SA 4.0"

  [params.comments]
  enabled = false
  provider = "disqus"

    [params.comments.disqusjs]

    [params.comments.utterances]
    issueTerm = "pathname"

    [params.comments.beaudar]
    issueTerm = "pathname"

    [params.comments.remark42]

    [params.comments.vssue]
    autoCreateIssue = false

    [params.comments.waline]
    emoji = [ "https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo" ]
    requiredMeta = [ "nick", "mail" ]

      [params.comments.waline.locale]
      admin = "Admin"

    [params.comments.twikoo]

    [params.comments.giscus]
    reactionsEnabled = 1
    emitMetadata = 0

    [params.comments.gitalk]

    [params.comments.cusdis]

  [params.widgets]
  homepage = [
    {type = "search"},
    {type = "archives", limit = 5},
    {type = "categories", limit = 6},
    {type = "tag-cloud", limit = 6}
    
   ]
  page = [ 
    {type = "search"},
    {type = "categories", limit = 6},
    {type = "tag-cloud", limit = 6},
    {type = "toc"}
  ]

[params.opengraph.twitter]
card = "summary_large_image"

[params.defaultImage.opengraph]
enabled = false
local = false

  [params.colorScheme]
  toggle = true
  default = "auto"

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true
